package wiring.bean;

public class Close implements Song {
	@Override
	public void singing() throws PerformanceException {
		String str = "Why do birds suddenly appear\n"
				+ "Every time you are near?\n"
				+ "Just like me,\n"
				+ "They long to be\n"
				+ "Close to you.\n"
				+ "\n"
				+ "Why do stars fall down from the sky\n"
				+ "Every time you walk by?\n"
				+ "Just like me,\n"
				+ "They long to be\n"
				+ "Close to you.\n"
				+ "\n"
				+ "On the day that you were born the angels got together\n"
				+ "And decided to create a dream come true.\n"
				+ "So, they sprinkled moon dust in your hair of gold\n"
				+ "And star light in your eyes of blue.\n"
				+ "\n"
				+ "That is why all the girls in town\n"
				+ "Follow you all around.\n"
				+ "Just like me,\n"
				+ "They long to be\n"
				+ "Close to you.\n"
				+ "\n"
				+ "On the day that you were born the angels got together\n"
				+ "And decided to create a dream come true.\n"
				+ "So, they sprinkled moon dust in your hair of gold\n"
				+ "And star light in your eyes of blue.\n"
				+ "\n"
				+ "That is why all the girls in town\n"
				+ "Follow you all around.\n"
				+ "Just like me,\n"
				+ "They long to be\n"
				+ "Close to you.\n"
				+ "\n"
				+ "Just like me,\n"
				+ "They long to be\n"
				+ "Close to you.\n"
				+ "\n"
				+ "Why? Close to you\n"
				+ "Why? Close to you\n"
				+ "Ha, close to you\n"
				+ "Why? Close to you";
		System.out.println("Close to you : "+str);
	}
}
